default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Cygnetise_development

test:
  <<: *default
  database: Cygnetise_test

production:
  <<: *default
  database: Cygnetise_production
  username: Cygnetise
  password: <%= ENV['CYGNETISE_DATABASE_PASSWORD'] %>
